name: Strona-Update
on:
  schedule:
    - cron: '0/5 * * * *'
  workflow_dispatch:
jobs:
  Data-Get:
    runs-on: self-hosted
    steps:
      - name: Data-Get
        run: |
             cd /home/ubuntu/
             sudo curl --request GET --url "https://api.github.com/repos/GrzesiuTorpeda/main/contents/.github/workflows" > data.json
             sudo cp /home/ubuntu/data.json /var/www/html/data.json
             
  Script-JS:
    runs-on: self-hosted
    steps:
      - name: script.js
        run: |
             cd /var/www/html/
             sudo touch script.js
             sudo sh -c 'cat << EOF > /var/www/html/script.js
             function change_myselect(sel) {
               const dbParam = JSON.stringify({table:sel,limit:20});
               const xmlhttp = new XMLHttpRequest();
               xmlhttp.onload = function() {
                 myObj = JSON.parse(this.responseText);
                 text = "<table border='1'>"
                 for (x in myObj) {
                   text += "<tr><td>" + myObj[x][sol] + "</td></tr>";
                 }
                 text += "</table>"    
                 document.getElementById("demo").innerHTML = text;
               }
               xmlhttp.open("POST", "data.json", true);
               xmlhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
               xmlhttp.send("x=" + dbParam);
             }
             EOF'
  

  HTML-Site:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: HTML-Site-Update
        run: |
             sudo sh -c 'cat << EOF > /var/www/html/index.html
             <html>
             <head>
             <title>AAA</title>
             </head>
             <body>
             <select id="myselect" onchange="change_myselect(this.value)">
               <option value="">Choose an option:</option>
               <option value="name">Name</option>
               <option value="path">Path</option>
               <option value="url">URL</option>
             </select>
             <p id="demo"></p>
             <script src="script.js"></script>
             </body>
             </html>
             EOF'
             
