name: Strona-Update
on:
  schedule:
    - cron: '5 * * * *'
    - cron: '10 * * * *'
    - cron: '15 * * * *'
    - cron: '20 * * * *'
    - cron: '25 * * * *'
    - cron: '30 * * * *'
    - cron: '35 * * * *'
    - cron: '40 * * * *'
    - cron: '45 * * * *'
    - cron: '50 * * * *'
    - cron: '55 * * * *'
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  HTML-Site:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: HTML-Site-Update
        run: |
             sudo sh -c 'cat << EOF > /var/www/html/index.html
             <html>
             <head>
             <title>AAA</title>
             <style>
             .dropbtn {
               background-color: #4CAF50;
               color: white;
               padding: 16px;
               font-size: 16px;
               border: none;
               cursor: pointer;
             }

             .dropdown {
               position: relative;
               display: inline-block;
             }

             .dropdown-content {
               display: none;
               position: absolute;
               background-color: #f9f9f9;
               min-width: 160px;
               box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
               z-index: 1;
             }

             .dropdown-content a {
               color: black;
               padding: 12px 16px;
               text-decoration: none;
               display: block;
             }

             .dropdown-content a:hover {background-color: #f1f1f1}

             .dropdown:hover .dropdown-content {
               display: block;
             }

             .dropdown:hover .dropbtn {
               background-color: #3e8e41;
             }
             </style>
             <script>
             </script>
             </head>
             <body>
             <div class="dropdown">
               <button class="dropbtn">Dropdown</button>
               <div class="dropdown-content">
               <a href="#">Amogos1</a>
               <a href="#">Amogos2</a>
               <a href="#">Amogos3</a>
               </div>
             </div>
             </body>
             </html>
             EOF'
             
