name: Strona-Update
on:
  schedule:
    - cron: '5 * * * *'
    - cron: '10 * * * *'
    - cron: '15 * * * *'
    - cron: '20 * * * *'
    - cron: '25 * * * *'
    - cron: '30 * * * *'
    - cron: '35 * * * *'
    - cron: '40 * * * *'
    - cron: '45 * * * *'
    - cron: '50 * * * *'
    - cron: '55 * * * *'
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  HTML-Site:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: HTML-Site-Update
        run: |
             
