name: Curl-API
on:
  workflow_dispatch:
jobs:
  Curl-Download:
    runs-on: self-hosted
    permissions:
      issues: read
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
             sudo apt install curl
  Curl-Workflows-Content:
    runs-on: self-hosted
    needs: Curl-Download
    permissions:
      issues: read
    steps:
      - env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
             cd /home/ubuntu/
             curl --request GET --url "https://api.github.com/repos/GrzesiuTorpeda/main/contents/.github/workflows" > data.json
             jq '.[] | {name,path}' data.json > newfile.json

  PHP-Database:
    runs-on: self-hosted
    needs: Curl-Workflows-Content
    
    steps:
      -  run: |
              sudo sh -c 'cat << EOF > /home/ubuntu/script.php
              <?php
                  "$mysqli" = new mysqli("localhost", "root", "ubuntu", "workflow");
                  if('$mysql'->connect_errno !=0){
                       echo '$mysqli'->connect_error;
                  }

                  '$json_data' = file_get_contents("newfile.json");
                  '$workflows' = json_decode('$json_data', JSON_OBJECT_AS_ARRAY);

                  '$stmt' = '$mysqli'->prepare("
                      INSERT INTO workflow(name,path)
                      VALUES(?,?)
                  ");
                  '$stmt'->bind_param("ssdi", '$name', '$path');

                  '$inserted_rows' = 0;
                  foreach ('$workflows' as '$workflow') {
                     '$name' = '$workflow'["name"];
                     '$path' = '$workflow'["path"];

                     '$stmt'->execute();
                     '$inserted_rows' ++;
                  }

                  if(count('$workflows') == '$inserted_rows'){
                      echo "success";
                  }else{
                      echo "error";
                  }
                  EOF'
      
