name: Curl-API
on:
  workflow_dispatch:
jobs:
  Curl-Download:
    runs-on: self-hosted
    permissions:
      issues: read
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
             sudo apt install curl
  Curl-Workflows-Content:
    runs-on: self-hosted
    needs: Curl-Download
    permissions:
      issues: read
    steps:
      - env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
             cd /home/ubuntu/
             curl --request GET --url "https://api.github.com/repos/GrzesiuTorpeda/main/contents/.github/workflows" \
             --header "name": "*.yml"> data.json

