name: Curl-API
on:
  workflow_dispatch:
jobs:
  Curl-Download:
    runs-on: self-hosted
    permissions:
      issues: read
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
             sudo apt install curl -y
  Curl-Workflows-Content:
    runs-on: self-hosted
    needs: Curl-Download
    permissions:
      issues: read
    steps:
      - env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
             cd /home/ubuntu/
             curl --request GET --url "https://api.github.com/repos/GrzesiuTorpeda/main/contents/.github/workflows" > data.json
  MySQL-Setup-Download:
    runs-on: self-hosted
    steps:
      - name: MariaDB-Download
        run: |
             echo "${{ secrets.USERPWD }}" | sudo  apt install mariadb-server -y
             sudo systemctl start mariadb
             sudo systemctl restart mariadb
  MySQL-Database:
    runs-on: self-hosted
    needs: MySQL-Setup-Download
    steps:
      - name: MySQL-Database
        run: |
              echo "${{ secrets.USERPWD }}" | sudo mysql -u root -h localhost -e "create database if not exists workflow; use workflow; create table if not exists workflow (name varchar(255), path varchar(255));"
  PHP-Download:
    runs-on: self-hosted
    steps:
      - name: PHP-Download
        run: |
             sudo  apt install php -y
  PHP-Database:
    runs-on: self-hosted
    needs: [Curl-Workflows-Content , MySQL-Database, PHP-Download]
    
    steps:
      -  run: |
              echo '<?php' > /home/ubuntu/script.php
              echo '  $mysqli = new mysqli("localhost", "root", "ubuntu", "workflow");' >> /home/ubuntu/script.php
              echo '  if ($mysqli->connect_errno != 0)' >> /home/ubuntu/script.php
              echo '  {' >> /home/ubuntu/script.php
              echo '      echo $mysqli->connect_error;' >> /home/ubuntu/script.php
              echo '  }' >> /home/ubuntu/script.php
              echo '  $json_data = file_get_contents("data.json");' >> /home/ubuntu/script.php
              echo '  $workflows = json_decode($json_data, JSON_OBJECT_AS_ARRAY);' >> /home/ubuntu/script.php
              echo '  $stmt = $mysqli->prepare("INSERT INTO workflow(name,path) VALUES(?,?)");' >> /home/ubuntu/script.php
              echo '  $stmt->bind_param("ss", $name, $path);' >> /home/ubuntu/script.php
              echo '  $inserted_rows = 0;' >> /home/ubuntu/script.php
              echo '  foreach ($workflows as $workflow)' >> /home/ubuntu/script.php
              echo '  {' >> /home/ubuntu/script.php
              echo '      $name = $workflow["name"];' >> /home/ubuntu/script.php
              echo '      $path = $workflow["path"];' >> /home/ubuntu/script.php
              echo '      $stmt->execute();' >> /home/ubuntu/script.php
              echo '      $inserted_rows ++;' >> /home/ubuntu/script.php
              echo '  }' >> /home/ubuntu/script.php
              echo '  if(count($workflows) == $inserted_rows){' >> /home/ubuntu/script.php
              echo '      echo "success";' >> /home/ubuntu/script.php
              echo '  } else {' >> /home/ubuntu/script.php
              echo '      echo "error";' >> /home/ubuntu/script.php
              echo '  }' >> /home/ubuntu/script.php
              echo '?>' >> /home/ubuntu/script.php
      - name: Execute PHP Script
        run: php /home/ubuntu/script.php
