name: Curl-API
on:
  workflow_dispatch:
jobs:
  Curl-Download:
    runs-on: self-hosted
    permissions:
      issues: read
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
              curl --request GET \
              --url "https://api.github.com/repos/octocat/Spoon-Knife/issues" \
              --header "Accept: application/vnd.github+json" \
              --header "Authorization: Bearer $GH_TOKEN"
  Curl-Workflows-Content:
    runs-on: self-hosted
    needs: Curl-Download
    permissions:
      issues: read
    steps:
      - env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
             curl --request GET --url "https://api.github.com/repos/GrzesiuTorpeda/main/contents/.github/workflows"

  Python-File-Create:
     runs-on: self-hosted
     needs: Curl-Workflows-Content
     steps:
       - run: |
             curl -i https://api.github.com/repos/GrzesiuTorpeda/main/contents/.github/workflows -o /home/ubuntu/workflow_files.json
             curl --request GET \
             --url "https://api.github.com/repos/GrzesiuTorpeda/main/issues?per_page=2" \
             --header "Accept: application/vnd.github+json" \
             --header "Authorization: Bearer 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" > data.json
