name: MySQL
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  MySQL-Setup-Download:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3

      
      - name: MariaDB-Download
        run: echo "${{ secrets.USERPWD }}" | sudo  apt install mariadb-server -y
        
  Database-Create:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Database-Creation
        run: |
             echo "${{ secrets.USERPWD }}" | sudo mysql -u root -h localhost -p"${{ secrets.MYSQL_ROOT_PASSWORD }}" -e create database a;
             create database a;
             
