name: MySQL
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  MySQL-Setup-Download:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3

      
      - name: MariaDB-Download
        run: echo ${{ secrets.USERPWD }} | sudo  apt install mariadb-server -y

      - name: Database MySQL
        run: |
             echo ${{ secrets.USERPWD }} | sudo mariadb -u root -h localhost
             create database a;
             
