name: MySQL
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  MySQL-Setup-Download:
    runs-on: self-hosted

    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      id-token: write
      issues: write
      discussions: write
      packages: write
      pages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
  
    steps:
      - uses: actions/checkout@v3

      
      - name: MariaDB-Download
        run: |
             sudo -s
             apt install mariadb-server -y
             
      - name: MariaDB-Check
        run: systemctl status mariadb
