name: MySQL
on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  MySQL-Setup-Download:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3

      
      - name: MariaDB-Download
        run: |
             echo "${{ secrets.USERPWD }}" | sudo  apt install mariadb-server -y
             sudo systemctl start mariadb
        
  Database-Create:
    runs-on: self-hosted
    needs: MySQL-Setup-Download
    steps:
      - uses: actions/checkout@v3

      - name: Database-Creation
        run: |
             echo "${{ secrets.USERPWD }}" | sudo mysql -u root -h localhost -p -e "create database a; use a; create table amongos (kolumna1 varchar(255), kolumna2 varchar(255), kolumna3 varchar(255));"
             mysql -u root -h localhost -e "use a; insert into amongos (kolumna1,kolumna2,kolumna3) values ('wartosc1','wartosc2','wartosc3'); select * from amongos;"
