name: MySQL
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  MySQL-Setup-Download:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Update
        run: apt update
      - name: MariaDB-Download
        run: apt install mariadb-server -y
