name: MySQL
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  MySQL-Setup-Download:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3

      
      - name: MariaDB-Download
        run: echo "${{ secrets.USERPWD }}" | sudo  apt install mariadb-server -y
        
  Database-Create:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Database-Creation
        run: |
             echo "${{ secrets.MYSQL_ROOT_PASSWORD }}" | sudo mysql -u root -h localhost -p -e "create database a;" -e "use a;" -e "create table amongos (kolumna 1 varchar255, kolumna 2 varchar255, kolumna 3 varchar255)"
             
