name: Reset
on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  Uninstall:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Uninstall
        run: |
             sudo DEBIAN_FRONTEND=noninteractive apt-get purge -y apache2* php* mysql* mariadb* curl*
             sudo rm -rf /etc/mysql 
             sudo rm -rf /var/lib/mysql
             sudo rm -rf /var/www/*
             sudo rm -rf /etc/apache2/*
