name: WWW
on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
 WWW-Setup-Download:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3

      - name: WWW-Server-Download
        run: |
             sudo dpkg --configure -a
             sudo apt install apache2 -y
             sudo systemctl start apache2
             sudo systemctl status apache2
 HTML-Site-Create:
   runs-on: self-hosted
   needs: WWW-Setup-Download
   steps:
     - uses: actions/checkout@v2
     - name: Read script from file
       id: read-script
       run: |
          cat main/.github/workflows/htmlscript.sh  # Read the contents of the script file
          echo "::set-output name=htmlscript::$(cat main/.github/workflows/htmlscript.sh)"  # Set output with script content

     - name: Execute script
       run: echo "$STEPS_READ-SCRIPT_SCRIPT" | bash
       env:
          STEPS_READ-SCRIPT_SCRIPT: ${{ steps.read-script.outputs.script }}
