name: WWW
on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
 WWW-Setup-Download:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3

      - name: WWW-Server-Download
        run: | 
             sudo apt install apache2 -y
             sudo systemctl start apache2
             sudo systemctl status apache2
      - name: Expect-Download
        run: sudo apt-get install -y expect
 HTML-Site-Create:
   runs-on: self-hosted
   steps:
     - uses: actions/checkout@v3

     - name: HTML-Site-Creation
       run: |
            cd /var/www/html/
            expect -c '
            spawn nano index.html
            send "<!DOCTYPE html>\r"
            send "<html>\r"
            send "<head>\r"
            send "<title>My Website</title>\r"
            send "</head>\r"
            send "<body>\r"
            send "<h1>Hello, world!</h1>\r"
            send "</body>\r"
            send "</html>\r"
            send "\x01"  # This sends Ctrl+X to exit Nano
            expect eof
            '
