name: WWW
on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
 WWW-Setup-Download:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3

      - name: WWW-Server-Download
        run: |
             sudo dpkg --configure -a
             sudo apt install apache2 -y
             sudo systemctl start apache2
             sudo systemctl status apache2
 HTML-Site-Create:
   runs-on: self-hosted
   needs: WWW-Setup-Download
   steps:
     - uses: actions/checkout@v3

     - name: HTML-Site-Creation
       run: |
            sudo sh -c 'cat << EOF > /var/www/html/index.html
            <!DOCTYPE html>
            <html>
            <head>
            <title>My Website</title>
            <style>
            p{color:red;}
            </style>
            </head>
            <body>
            <h1>Hello, world!</h1>
            <p>amongos</p>
            </body>
            </html>
            EOF'
