name: WWW
on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
 WWW-Setup-Download:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3

      - name: WWW-Server-Download
        run: | 
             sudo apt install apache2 -y
             sudo systemctl start apache2
             sudo systemctl status apache2
