name: WWW
on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
 WWW-Setup-Download:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3

      - name: WWW-Server-Download
        run: | 
             sudo apt install apache2 -y
             sudo systemctl start apache2
             sudo systemctl status apache2
      - name: Expect-Download
        run: sudo apt-get install -y expect
 HTML-Site-Create:
   runs-on: self-hosted
   steps:
     - uses: actions/checkout@v3

     - name: HTML-Site-Creation
       run: |
            cat << EOF > /var/www/html/index.html
            <!DOCTYPE html>
            <html>
            <head>
            <title>My Website</title>
            </head>
            <body>
            <h1>Hello, world!</h1>
            </body>
            </html>
            EOF
